name: Main CI Workflow
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  
jobs:
  build:
    name: Build Laravel App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Laravel App
        uses: ./.github/workflows/build

  test:
    name: Test the Application
    runs-on: ubuntu-latest
    needs: [build]
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USERNAME: root
          MYSQL_DATABASE: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test the Application
        uses:  ./.github/workflows/test